// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class ekiden : Exchange
{
    public ekiden (object args = null): base(args) {}

    public async Task<object> v1PublicGetMarketCandles (object parameters = null)
    {
        return await this.callAsync ("v1PublicGetMarketCandles",parameters);
    }

    public async Task<object> v1PublicGetMarketCandlesStatsMarketAddr (object parameters = null)
    {
        return await this.callAsync ("v1PublicGetMarketCandlesStatsMarketAddr",parameters);
    }

    public async Task<object> v1PublicGetMarketMarketInfo (object parameters = null)
    {
        return await this.callAsync ("v1PublicGetMarketMarketInfo",parameters);
    }

    public async Task<object> v1PublicGetMarketFills (object parameters = null)
    {
        return await this.callAsync ("v1PublicGetMarketFills",parameters);
    }

    public async Task<object> v1PublicGetMarketOrders (object parameters = null)
    {
        return await this.callAsync ("v1PublicGetMarketOrders",parameters);
    }

    public async Task<object> v1PrivateGetUserOrders (object parameters = null)
    {
        return await this.callAsync ("v1PrivateGetUserOrders",parameters);
    }

    public async Task<object> v1PrivatePostUserIntent (object parameters = null)
    {
        return await this.callAsync ("v1PrivatePostUserIntent",parameters);
    }

    public async Task<object> v1PrivatePostUserIntentCommit (object parameters = null)
    {
        return await this.callAsync ("v1PrivatePostUserIntentCommit",parameters);
    }

}