// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *ekiden) V1PublicGetMarketCandles (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PublicGetMarketCandles", args...)
}

func (this *ekiden) V1PublicGetMarketCandlesStatsMarketAddr (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PublicGetMarketCandlesStatsMarketAddr", args...)
}

func (this *ekiden) V1PublicGetMarketMarketInfo (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PublicGetMarketMarketInfo", args...)
}

func (this *ekiden) V1PublicGetMarketFills (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PublicGetMarketFills", args...)
}

func (this *ekiden) V1PublicGetMarketOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PublicGetMarketOrders", args...)
}

func (this *ekiden) V1PrivateGetUserOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PrivateGetUserOrders", args...)
}

func (this *ekiden) V1PrivateGetUserPortfolio (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PrivateGetUserPortfolio", args...)
}

func (this *ekiden) V1PrivateGetUserPositions (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PrivateGetUserPositions", args...)
}

func (this *ekiden) V1PrivatePostUserIntent (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PrivatePostUserIntent", args...)
}

func (this *ekiden) V1PrivatePostUserIntentCommit (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("v1PrivatePostUserIntentCommit", args...)
}
