<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class ekiden extends \ccxt\Exchange {
    public function v1_public_get_market_candles($params = array()) {
        return $this->request('market/candles', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_public_get_market_candles_stats_market_addr($params = array()) {
        return $this->request('market/candles/stats/{market_addr}', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_public_get_market_market_info($params = array()) {
        return $this->request('market/market_info', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_public_get_market_fills($params = array()) {
        return $this->request('market/fills', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_public_get_market_orders($params = array()) {
        return $this->request('market/orders', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_private_get_user_orders($params = array()) {
        return $this->request('user/orders', array('v1', 'private'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_private_get_user_portfolio($params = array()) {
        return $this->request('user/portfolio', array('v1', 'private'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_private_get_user_positions($params = array()) {
        return $this->request('user/positions', array('v1', 'private'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1_private_post_user_intent($params = array()) {
        return $this->request('user/intent', array('v1', 'private'), 'POST', $params, null, null, array("cost" => 1));
    }
    public function v1_private_post_user_intent_commit($params = array()) {
        return $this->request('user/intent/commit', array('v1', 'private'), 'POST', $params, null, null, array("cost" => 1));
    }
    public function v1PublicGetMarketCandles($params = array()) {
        return $this->request('market/candles', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PublicGetMarketCandlesStatsMarketAddr($params = array()) {
        return $this->request('market/candles/stats/{market_addr}', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PublicGetMarketMarketInfo($params = array()) {
        return $this->request('market/market_info', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PublicGetMarketFills($params = array()) {
        return $this->request('market/fills', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PublicGetMarketOrders($params = array()) {
        return $this->request('market/orders', array('v1', 'public'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PrivateGetUserOrders($params = array()) {
        return $this->request('user/orders', array('v1', 'private'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PrivateGetUserPortfolio($params = array()) {
        return $this->request('user/portfolio', array('v1', 'private'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PrivateGetUserPositions($params = array()) {
        return $this->request('user/positions', array('v1', 'private'), 'GET', $params, null, null, array("cost" => 1));
    }
    public function v1PrivatePostUserIntent($params = array()) {
        return $this->request('user/intent', array('v1', 'private'), 'POST', $params, null, null, array("cost" => 1));
    }
    public function v1PrivatePostUserIntentCommit($params = array()) {
        return $this->request('user/intent/commit', array('v1', 'private'), 'POST', $params, null, null, array("cost" => 1));
    }
}
